name: woxxy
description: LAN File Sharing App
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  network_info_plus: ^4.1.0
  desktop_drop: ^0.4.4
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  filesize: ^2.0.1
  window_manager: ^0.3.7
  rxdart: ^0.27.7
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  path: ^1.8.3
  url_launcher: ^6.2.2
  crypto: ^3.0.3
  tray_manager: ^0.2.4
  flutter_local_notifications: ^18.0.0
  local_notifier: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icons/head.png"
  image_path_ios: "assets/icons/head.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/head.png"
  windows:
    generate: true
    image_path: "assets/icons/head.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/head.png"
  linux:
    generate: true
    image_path: "assets/icons/head.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
